import ReactQueryProvider from '@/context/ReactQueryProvider';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <div className="flex flex-col min-h-screen">
        <main className="flex-grow flex">{children}</main>
      </div>
    </ReactQueryProvider>
  );
}
